{
  "repository": {
    "name": "traneio/ndbc",
    "githubId": 84398452,
    "url": "https://github.com/traneio/ndbc",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 430339065,
      "url": "http://travis-ci.org/traneio/ndbc/builds/430339065",
      "date": "Sep 19, 2018 5:18:37 AM"
    }
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Sep 19, 2018 5:18:23 AM",
    "reproductionDateEnd": "Sep 19, 2018 5:21:39 AM",
    "totalDuration": 191,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 3,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          3
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 23,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          23
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 134,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          134
        ]
      }
    },
    "projectRootPomPath": "./workspace/traneio/ndbc/430339065/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "projectMetrics": {
    "numberModules": 10,
    "numberSourceFiles": 191,
    "numberTestFiles": 70,
    "numberLibrariesFailingModule": 18
  },
  "tests": {
    "failingModule": "/root/workspace/traneio/ndbc/430339065/ndbc-postgres-netty4",
    "overallMetrics": {
      "numberRunning": 375,
      "numberPassing": 269,
      "numberFailing": 0,
      "numberErroring": 106,
      "numberSkipping": 9,
      "failures": [
        {
          "failureName": "io.trane.future.TimeoutException$1",
          "isError": true,
          "occurrences": 3
        },
        {
          "failureName": "io.trane.future.CheckedFutureException",
          "isError": true,
          "occurrences": 103
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "numberRunning": 56,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 56,
        "numberSkipping": 4
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "numberRunning": 28,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 28,
        "numberSkipping": 0
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "numberRunning": 22,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 22,
        "numberSkipping": 4
      }
    ],
    "failureDetails": [
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateWithParam[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryNoParamsFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryWithParamsFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "booleanArray[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localDateTimeArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdteWithParamFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localTime[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "long_[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteUpdateFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "byteArrayArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "integerArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "integer[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteDelete[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQueryFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "short_[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateNoParamFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionSuccess[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteInsertFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteNoParam[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "byteArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQueryInvalid[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryInvalid[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionDBFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localTime[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertWithParamFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryNoParamsFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteWithParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryNoParams[PG V9_6]",
        "failureName": "io.trane.future.TimeoutException$1",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateNoParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "double_[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteInsertFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteInsert[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryWithParams[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localDate[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localDateTime[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateNoParam[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "shortArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "bigDecimal[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "byte_[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertNoParam[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "shortArray[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "doubleArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "string[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQuery[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQueryInvalid[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "longArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localDateArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localDateTime[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localTimeArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteWithParamFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteNoParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertWithParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertWithParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "string[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionSuccess[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "_boolean[PG V9_5]",
        "failureName": "io.trane.future.TimeoutException$1",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteUpdate[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryInvalid[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateNoParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "offsetTime[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localTimeArray[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "integer[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteUpdateFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "bigDecimalArray[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "short_[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "double_[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteUpdate[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localDateTimeArray[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteDeleteFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQuery[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "bigDecimal[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertNoParamFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteWithParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateWithParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "booleanArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "byteArrayArray[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteInsert[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "float_[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteDeleteFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "offsetTimeArray[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "long_[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "float_[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "byteArray[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdteWithParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertWithParam[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localDateArray[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionDBFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "offsetTime[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertNoParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertNoParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "longArray[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteNoParamFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "integerArray[PG V9_5]",
        "failureName": "io.trane.future.TimeoutException$1",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "byte_[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteDelete[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "offsetTimeArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "_boolean[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteWithParam[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "bigDecimalArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryWithParams[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteNoParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryNoParams[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQueryFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localDate[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:44655",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryWithParamsFailure[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "doubleArray[PG V9_5]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:34785",
        "isError": true
      }
    ]
  },
  "commits": {
    "buggyBuild": {
      "repoName": "traneio/ndbc",
      "branchName": "master",
      "sha": "ae9cc5c87dc0fd7ee5b350adbeef889e1d338d70",
      "url": "http://github.com/traneio/ndbc/commit/ae9cc5c87dc0fd7ee5b350adbeef889e1d338d70",
      "date": "Sep 19, 2018 3:53:12 AM"
    }
  },
  "type": "only_fail"
}