{
  "repository": {
    "name": "traneio/ndbc",
    "githubId": 84398452,
    "url": "https://github.com/traneio/ndbc",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 435404928,
      "url": "http://travis-ci.org/traneio/ndbc/builds/435404928",
      "date": "Oct 1, 2018 3:29:33 AM"
    }
  },
  "tests": {
    "failingModule": "/root/workspace/traneio/ndbc/435404928/ndbc-postgres-netty4",
    "overallMetrics": {
      "numberRunning": 325,
      "numberPassing": 269,
      "numberFailing": 0,
      "numberErroring": 56,
      "numberSkipping": 1,
      "failures": [
        {
          "failureName": "io.trane.future.CheckedFutureException",
          "isError": true,
          "occurrences": 56
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "numberRunning": 29,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 29,
        "numberSkipping": 1
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "numberRunning": 14,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 14,
        "numberSkipping": 0
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "numberRunning": 13,
        "numberPassing": 0,
        "numberFailing": 0,
        "numberErroring": 13,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "floatArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteDeleteFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "integer[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "double_[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "longArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "_boolean[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "byte_[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdteWithParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryNoParams[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteUpdateFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertNoParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteWithParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "byteArrayArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "shortArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteInsertFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQuery[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateNoParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteInsert[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionLocalFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQueryFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionSuccess[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localTimeArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "long_[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryInvalid[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "string[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localDateTimeArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateWithParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryWithParamsFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteDelete[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localDate[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "offsetTimeArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "short_[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localTime[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "booleanArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleQueryInvalid[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "offsetTime[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertNoParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertWithParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "simpleExecuteUpdate[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "integerArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteNoParamFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "stringArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryNoParamsFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "bigDecimalArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "byteArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteUpdateNoParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteWithParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "localDateTime[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "float_[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "transactionDBFailure[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteDeleteNoParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedExecuteInsertWithParam[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "doubleArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresScalarEncodingTest",
        "testMethod": "bigDecimal[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresArrayEncodingTest",
        "testMethod": "localDateArray[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      },
      {
        "testClass": "io.trane.ndbc.postgres.netty4.PostgresDataSourceTest",
        "testMethod": "extendedQueryWithParams[PG V9_6]",
        "failureName": "io.trane.future.CheckedFutureException",
        "detail": "io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:36579",
        "isError": true
      }
    ]
  },
  "projectMetrics": {
    "numberModules": 10,
    "numberSourceFiles": 198,
    "numberTestFiles": 70,
    "numberLibrariesFailingModule": 20
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Oct 1, 2018 3:28:59 AM",
    "reproductionDateEnd": "Oct 1, 2018 3:30:54 AM",
    "totalDuration": 112,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 4,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          4
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 23,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          23
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 57,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          57
        ]
      }
    },
    "projectRootPomPath": "./workspace/traneio/ndbc/435404928/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "commits": {
    "buggyBuild": {
      "repoName": "traneio/ndbc",
      "branchName": "master",
      "sha": "de7acac5de6d057552de9a45746457a1720a1605",
      "url": "http://github.com/traneio/ndbc/commit/de7acac5de6d057552de9a45746457a1720a1605",
      "date": "Oct 1, 2018 3:24:18 AM"
    }
  },
  "type": "only_fail"
}