{
  "repository": {
    "name": "xemime-lang/xemime",
    "githubId": 101529535,
    "url": "https://github.com/xemime-lang/xemime",
    "isFork": false,
    "original": {
      "name": "",
      "githubId": 0,
      "url": ""
    },
    "isPullRequest": false,
    "pullRequestId": 0
  },
  "builds": {
    "buggyBuild": {
      "id": 440483535,
      "url": "http://travis-ci.org/xemime-lang/xemime/builds/440483535",
      "date": "Oct 12, 2018 7:52:55 AM"
    }
  },
  "tests": {
    "failingModule": "/root/workspace/xemime-lang/xemime/440483535",
    "overallMetrics": {
      "numberRunning": 48,
      "numberPassing": 45,
      "numberFailing": 3,
      "numberErroring": 0,
      "numberSkipping": 0,
      "failures": [
        {
          "failureName": "java.lang.AssertionError",
          "isError": false,
          "occurrences": 3
        }
      ]
    },
    "failingClasses": [
      {
        "testClass": "net.zero918nobita.xemime.DoubleTest",
        "numberRunning": 18,
        "numberPassing": 16,
        "numberFailing": 2,
        "numberErroring": 0,
        "numberSkipping": 0
      },
      {
        "testClass": "net.zero918nobita.xemime.BoolTest",
        "numberRunning": 17,
        "numberPassing": 16,
        "numberFailing": 1,
        "numberErroring": 0,
        "numberSkipping": 0
      }
    ],
    "failureDetails": [
      {
        "testClass": "net.zero918nobita.xemime.BoolTest",
        "testMethod": "testSub",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of net.zero918nobita.xemime.ast.FatalException and exception with message a string containing \"0: インタプリタ内部の深刻なエラーが発生しました。 [99]\")      but: exception with message a string containing \"0: インタプリタ内部の深刻なエラーが発生しました。 [99]\" message was \"0: インタプリタ内部の深刻なエラーが発生しました。 [98]\" Stacktrace was: net.zero918nobita.xemime.ast.FatalException: 0: インタプリタ内部の深刻なエラーが発生しました。 [98]  at net.zero918nobita.xemime.ast.Node.add(Node.kt:15)  at net.zero918nobita.xemime.ast.Node.sub(Node.kt:27)  at net.zero918nobita.xemime.BoolTest.testSub(BoolTest.java:65)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) ",
        "isError": false
      },
      {
        "testClass": "net.zero918nobita.xemime.DoubleTest",
        "testMethod": "testSub",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: is \"0.1\"      but: was \"0.30000000000000004\"",
        "isError": false
      },
      {
        "testClass": "net.zero918nobita.xemime.DoubleTest",
        "testMethod": "testSub2",
        "failureName": "java.lang.AssertionError",
        "detail": " Expected: (an instance of net.zero918nobita.xemime.ast.FatalException and exception with message a string containing \"0: インタプリタ内部の深刻なエラーが発生しました。 [121]\")      but: exception with message a string containing \"0: インタプリタ内部の深刻なエラーが発生しました。 [121]\" message was \"0: インタプリタ内部の深刻なエラーが発生しました。 [120]\" Stacktrace was: net.zero918nobita.xemime.ast.FatalException: 0: インタプリタ内部の深刻なエラーが発生しました。 [120]  at net.zero918nobita.xemime.entity.Double.add(Double.java:57)  at net.zero918nobita.xemime.entity.Double.add(Double.java:9)  at net.zero918nobita.xemime.ast.Node.sub(Node.kt:27)  at net.zero918nobita.xemime.DoubleTest.testSub2(DoubleTest.java:60)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)  at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)  at org.junit.rules.RunRules.evaluate(RunRules.java:20)  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)  at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)  at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)  at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)  at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)  at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) ",
        "isError": false
      }
    ]
  },
  "projectMetrics": {
    "numberModules": 1,
    "numberSourceFiles": 100,
    "numberTestFiles": 9,
    "numberLibrariesFailingModule": 11
  },
  "reproductionBuggyBuild": {
    "reproductionDateBeginning": "Oct 12, 2018 7:54:03 AM",
    "reproductionDateEnd": "Oct 12, 2018 7:55:28 AM",
    "totalDuration": 83,
    "processDurations": {
      "cloning": {
        "nbSteps": 1,
        "totalDuration": 3,
        "stepNames": [
          "CloneRepository"
        ],
        "stepDurations": [
          3
        ]
      },
      "building": {
        "nbSteps": 2,
        "totalDuration": 33,
        "stepNames": [
          "CheckoutBuggyBuild",
          "BuildProject"
        ],
        "stepDurations": [
          0,
          33
        ]
      },
      "testing": {
        "nbSteps": 1,
        "totalDuration": 17,
        "stepNames": [
          "TestProject"
        ],
        "stepDurations": [
          17
        ]
      }
    },
    "projectRootPomPath": "./workspace/xemime-lang/xemime/440483535/pom.xml"
  },
  "patchDiff": {
    "files": {
      "numberAdded": 0,
      "numberChanged": 0,
      "numberDeleted": 0
    },
    "lines": {
      "numberAdded": 0,
      "numberDeleted": 0
    }
  },
  "commits": {
    "buggyBuild": {
      "repoName": "xemime-lang/xemime",
      "branchName": "master",
      "sha": "d4068c58620806d595a12b4cdcffa9344e8133aa",
      "url": "http://github.com/xemime-lang/xemime/commit/d4068c58620806d595a12b4cdcffa9344e8133aa",
      "date": "Oct 12, 2018 7:51:07 AM"
    }
  },
  "type": "only_fail"
}