-------------------------------------------------------------------------------
Test set: br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest
-------------------------------------------------------------------------------
Tests run: 10, Failures: 0, Errors: 10, Skipped: 0, Time elapsed: 10.13 s <<< FAILURE! - in br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest
testBuscarFuncionarioPorCpf(br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest)  Time elapsed: 1.969 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)

testBuscarFuncionarioPorCpf(br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest)  Time elapsed: 1.97 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)

testBucarFuncionarioPorEmailECpf(br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest)  Time elapsed: 2.026 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)

testBucarFuncionarioPorEmailECpf(br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest)  Time elapsed: 2.027 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)

testBuscarFuncionarioPorEmail(br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest)  Time elapsed: 2.023 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)

testBuscarFuncionarioPorEmail(br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest)  Time elapsed: 2.025 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)

testBuscarFuncionarioPorEmailECpfParaCpfInvalido(br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest)  Time elapsed: 2.035 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)

testBuscarFuncionarioPorEmailECpfParaCpfInvalido(br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest)  Time elapsed: 2.035 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)

testBuscarFuncionarioPorEmailECpfParaEmailInvalido(br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest)  Time elapsed: 2.052 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.setUp(FuncionarioRepositoryTest.java:38)

testBuscarFuncionarioPorEmailECpfParaEmailInvalido(br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest)  Time elapsed: 2.053 s  <<< ERROR!
org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at br.com.modelo.pontointeligente.api.repositories.FuncionarioRepositoryTest.tearDown(FuncionarioRepositoryTest.java:44)

