-------------------------------------------------------------------------------
Test set: ru.vorotov.library.dao.data.DataJpaBookRepositoryTestTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 30.041 s <<< FAILURE! - in ru.vorotov.library.dao.data.DataJpaBookRepositoryTestTest
testGet(ru.vorotov.library.dao.data.DataJpaBookRepositoryTestTest)  Time elapsed: 30.021 s  <<< ERROR!
org.springframework.dao.DataAccessResourceFailureException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]; nested exception is com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
	at ru.vorotov.library.dao.data.DataJpaBookRepositoryTestTest.testGet(DataJpaBookRepositoryTestTest.java:19)
Caused by: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused (Connection refused)}}]
	at ru.vorotov.library.dao.data.DataJpaBookRepositoryTestTest.testGet(DataJpaBookRepositoryTestTest.java:19)

